### ISSUE TITLE
Crashed tests reported as success in VSCode devcontainer

### ISSUE THREAD

**Issue by motus** [microsoft/MLOS#559]
e.g., running `test_ssh_host_service.py::test_ssh_service_remote_exec` (currently failing due to #558) appears as passed in VSCode.

pytest output:
```
>>>PYTHON-EXEC-OUTPUT
CLIENT: Server listening on port 46607...
Received JSON data in run script
/workspaces/MLOS/conftest.py:26: UserWarning: DISPLAY environment variable is set, which can cause problems in some setups (e.g. WSL). Adjusting matplotlib backend to "agg" to compensate.
  warn(UserWarning('DISPLAY environment variable is set, which can cause problems in some setups (e.g. WSL). '
============================= test session starts ==============================
platform linux -- Python 3.11.5, pytest-7.4.3, pluggy-1.3.0 -- /opt/conda/envs/mlos/bin/python
cachedir: .pytest_cache
rootdir: /workspaces/MLOS
configfile: setup.cfg
plugins: cov-4.1.0, forked-1.6.0, docker-2.0.1, local-badge-1.0.3, anyio-3.5.0, xdist-3.3.1, lazy-fixture-0.6.3, typeguard-3.0.2
created: 1/1 worker
/workspaces/MLOS/conftest.py:26: UserWarning: DISPLAY environment variable is set, which can cause problems in some setups (e.g. WSL). Adjusting matplotlib backend to "agg" to compensate.
  warn(UserWarning('DISPLAY environment variable is set, which can cause problems in some setups (e.g. WSL). '
1 worker [1 item]

scheduling tests via LoadScheduling

mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_host_service.py::test_ssh_service_remote_exec 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/_pytest/main.py", line 325, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/xdist/dsession.py", line 122, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/xdist/dsession.py", line 145, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/xdist/dsession.py", line 283, in worker_testreport
INTERNALERROR>     self.config.hook.pytest_runtest_logreport(report=rep)
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/_pytest/terminal.py", line 574, in pytest_runtest_logreport
INTERNALERROR>     *self.config.hook.pytest_report_teststatus(report=rep, config=self.config)
INTERNALERROR>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/opt/conda/envs/mlos/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/vscode/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/vscode_pytest/__init__.py", line 203, in pytest_report_teststatus
INTERNALERROR>     node_path = map_id_to_path[report.nodeid]
INTERNALERROR>                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
INTERNALERROR> KeyError: 'mlos_bench/mlos_bench/tests/services/remote/ssh/test_ssh_host_service.py::test_ssh_service_remote_exec'

============================ no tests ran in 17.62s ============================
<<<PYTHON-EXEC-OUTPUT
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=2, type=1, proto=0, laddr=('127.0.0.1', 37302), raddr=('127.0.0.1', 46607)>
```

**Comment by bpkroth** [comment]
Possibly related:
https://github.com/microsoft/vscode-python/issues/19374

**Comment by motus** [comment]
hmm, looks like the tests in `launcher_parse_args_test.py` fail in VSCode + WSL devcontainer, and that probably triggers the behavior of the pytest plugin. Here's the failure that I get on my PC:
```
>       assert path_join(launcher.global_config["pathVarWithEnvVarRef"], abs_path=True) \
            == path_join(expected_root_pwd, "foo", abs_path=True)
E       AssertionError: assert '/workspaces/MlosCore/foo' == '/vscode/vscode-server/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc/foo'
E         - /vscode/vscode-server/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc/foo
E         + /workspaces/MlosCore/foo
```
(that's in `mlos_bench/mlos_bench/tests/launcher_parse_args_test.py::test_launcher_args_parse_2` line `123`

**Comment by bpkroth** [comment]
I think #570 should have fixed some of these, but please reopen if necessary.
